os:
  - linux

dist: xenial

language: php

php:
  - '7.3'

services:
  - mysql

notifications:
  email:
    recipients:
      - edoardo.savini@fablabromagna.org
    on_success: always
    on_failure: always

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate --env=travis
  - cp .env.travis .env.testing

before_install:
  - mysql -e 'CREATE DATABASE lemonade CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

script:
  - vendor/bin/phpunit
